### ISSUE TITLE
Webpack 4 not including asset

### ISSUE THREAD

**Issue by darkenvy** [jharris4/html-webpack-include-assets-plugin#30] opened 2018-06-29 23:22 UTC
Does this work with Webpack4? I can find the asset just fine (using the copy plugin as directed) but `html-webpack-include-assets-plugin` never adds anything to the html.

webpack: 4.14.0
html-webpack-include-assets-plugin: 1.0.4

**Comment by caravinci** [comment] 2018-08-02 14:53
To add some info, in my project we have the latest packages for all the Webpack + Babel dependencies as of today. the output is `<script src="undefined"></script>` where it used to inject a JS file correctly on Webpack 3.
I could PR a fix if anyone points me in the right direction?

**Comment by jharris4** [comment] 2018-08-02 17:29
Sorry for the delay on this. I'm currently using this plugin with webpack 4, but had been using it just fine with webpack 3 before that.

I suspect that any issues where the plugin is not working as expected with either of these versions is due to a specific configuration that's being used.

I can try to help dig into it a little if you can provide a reproducible example...

**Comment by caravinci** [comment] 2018-08-02 18:29
In my case: 
```
new HtmlWebpackIncludeAssetsPlugin({
    append: true,
    assets: ['js/plugins/moment/moment-with-locales.min.js']
});
```
Turns into `<script src="undefined"></script>`

@jharris4 Ideas?

**Comment by jharris4** [comment] 2018-08-02 18:41
@caravinci without a runnable example, it's hard for me to see anything wrong.

You can look at the unit tests here, they have a bunch of tests/examples that are all currently working with webpack 3 (and I've run them locally with webpack 4 too).

Maybe try and copy and paste examples from the unit tests and make sure they work with your setup, and then try to pinpoint the issue?

Also, what version of the various plugins are you using?

**Comment by caravinci** [comment] 2018-08-02 19:06
Fair enough. I'm just not sure what to show you (perhaps the whole webpack.config file?) as I'm not able to give you a runnable version of the app I'm working on (private repos and all that).

I'll try the Jasmine approach you suggest and see what I can get. It just seems odd that the bare basic example works well on Webpack 3, yet breaks on 4. Could be some plugin hook issue, would be my best guess, but I'm simply not able to troubleshoot that far.

**Comment by jharris4** [comment] 2018-08-02 19:11
Ya, I have the same problem, most of the stuff I use these plugins for is proprietary which makes it hard to post examples.

I do have another plugin which uses this plugin, and has tests that pass when using webpack 4, so I can definitely confirm that this plugin works with both webpack 3 & 4, but maybe you need to track down what's different in your webpack config versus the various examples in the tests.

If you're interested, the plugin is: https://github.com/jharris4/html-webpack-deploy-assets-plugin

And the tests are: https://github.com/jharris4/html-webpack-deploy-assets-plugin/blob/master/test/index_spec.js

**Comment by caravinci** [comment] 2018-08-02 19:15
oooh I like that one, I could potentially use it instead, and could fix my issue (albeit not the issue on this plugin, if there really is one at all).

Let me check and get back to you. Thanks! :+1:

**Comment by c0ldcat** [comment] 2018-08-03 04:31
It seems breaks only when using html-webpack-plugin@4.0.0-alpha.
b252108bdba77c2354d53ee4ab72d157dfee4fc3 maybe fix it

**Comment by caravinci** [comment] 2018-08-03 13:02
That commit (which seems to be missing from the master timeline) gives me an idea on how to deal with that. May be able to open a PR later. Setting a reminder for this.

Thanks @jharris4 @c0ldcat for your attention.

**Comment by jharris4** [comment] 2018-08-03 13:59
Ah yes, there are breaking changes in the API for the alpha version of `html-webpack-plugin` and they actually did give warning:

https://github.com/jantimon/html-webpack-plugin/issues/971

I haven't had the time to look into it yet, but you're more than welcome to make a PR! :-)

PS. @caravinci Are you from Toronto? I'm actually driving there today! :-)

**Comment by caravinci** [comment] 2018-08-03 16:13
haha hit me up. I'm free this weekend and we can hang out.

**Comment by ganesharulanantham** [comment] 2018-08-20 17:52
@jharris4 and @caravinci Ooops. Any tentative fix plan? or Should I downgrade to webpack 3?

**Comment by jharris4** [comment] 2018-08-20 18:09
@ganesharulanantham the plugin works with webpack 4. It’s the beta version of `html-webpack-plugin` that it doesn’t work with yet

**Comment by danburzo** [comment] 2018-08-23 07:16
Hmm, I can't seem to make the plugin include any assets using

```js
  "html-webpack-include-assets-plugin": "^1.0.4",
  "html-webpack-plugin": "^3.2.0",
  "webpack": "^4.16.5",
```

and:

```js
plugins: [
  new HtmlWebpackPlugin({
    chunks: ['mychunk'],
    template: path.join(process.cwd(), 'mytemplate.html'),
    filename: 'myfile.html'
  }),
  new HtmlWebpackIncludeAssetsPlugin({
    files: ['myfile.html'],
    assets: {
      path: '<some/path/to/cdn>',
      type: 'css'
     },
    append: true
  })
]
```

Debugging the code I noticed that:

```
compilation.hooks.htmlWebpackPluginBeforeHtmlGeneration.tapAsync('htmlWebpackIncludeAssetsPlugin', onBeforeHtmlGeneration);
compilation.hooks.htmlWebpackPluginAlterAssetTags.tapAsync('htmlWebpackIncludeAssetsPlugin', onAlterAssetTag);
```

this doesn't seem to have any effect? (the two methods are not called throughout the process)

**Comment by danburzo** [comment] 2018-08-23 14:28
No problem, @jharris4! I've sorted it out from my webpack config, for now.

**Comment by jharris4** [comment] 2018-09-19 06:34
Version `1.0.5` has just been released with support for the new API introduced in `html-webpack-plugin` 4.X+, and all unit tests are now run on webpack 4.x instead of webpack 3.x.

**Closed by jharris4** 2018-09-19 06:34 UTC

**Comment by danburzo** [comment] 2018-09-19 07:58
Perfect, thank you!
