### ISSUE TITLE
Why would webpack-cli require html-webpack-include-assets-plugin

### ISSUE THREAD

**Issue by blachawk** [jharris4/html-webpack-include-assets-plugin#40] opened 2019-02-01 17:44 UTC
I am getting a strange error and don't  understand why its happening via npm.

I have the following npm packages installed:

```
"devDependencies": {
    "@fortawesome/fontawesome": "^1.1.8",
    "@fortawesome/fontawesome-free-solid": "^5.0.13",
    "bootstrap": "^4.1.1",
    "css-loader": "^0.28.11",
    "exports-loader": "^0.7.0",
    "html-webpack-plugin": "^3.2.0",
    "jquery": "^3.3.1",
    "json-loader": "^0.5.7",
    "mini-css-extract-plugin": "^0.4.0",
    "node-sass": "^4.9.0",
    "popper.js": "^1.14.3",
    "postcss-loader": "^2.1.5",
    "sass-loader": "^7.0.3",
    "webpack": "^4.12.0",
    "webpack-cli": "^3.2.1",
    "webpack-dev-server": "^3.1.4"
  },
``` 

when I run npm start from the terminal, I get the following error message:

```
C:\Users\...\node_modules\webpack-cli\bin\cli.js:235
                                throw err;
                                ^
Error: Cannot find module 'html-webpack-include-assets-plugin'
```

Why is this happening to me?

**Comment by jharris4** [comment] 2019-02-01 18:54
Sounds like you have it in your webpack config. Try doing a text search across all files maybe?

**Comment by blachawk** [comment] 2019-02-01 19:08
Yeah I did that.  Nothing comes up.  So strange.  My Webpack environment runs great with it.  I don't mind holding on to it in development, but I wish I knew why npm is complaining about it when its gone...

**Comment by jharris4** [comment] 2019-02-01 21:23
Very strange, it must be loading the plugin from somewhere, in some kind of `webpack.config.js` file would be my bet.

I don't think there's much I can do to help, since the issue is actually outside of this plugin somewhere.

Gonna close it, good luck tracking down where config is that's causing your error!

**Closed by jharris4** 2019-02-01 21:23 UTC
