### ISSUE TITLE
GLOB not working as intended

### ISSUE THREAD

**Issue by dylanharty** [jharris4/html-webpack-include-assets-plugin#16] opened 2017-11-10 16:34 UTC
Problem: CSS files are not being included in the HTML document correctly if using GLOB from this library. However, if i use glob.sync before to create an array of assets before the `new HtmlWebpackIncludeAssetsPlugin`, it works fine(same pattern).

HtmlWebpackIncludeAssetsPlugin

```
new HtmlWebpackIncludeAssetsPlugin({
          publicPath: './assets/',
          assets: [{path: 'css', glob: '*/assets/css/*.css', globPath: 'src/modules/', type: 'css'}],
          append: false
 }),
```
The above should use the GLOB pattern 'src/modules/*/assets/css/*.css' to find matching files. However even if the file exists, it will not add the correct name into the HTML file. For example a file ''src/modules/core/assets/css/test.css' will be added to the HTML file as `<link href="/assets/css" rel="stylesheet">`

Maybe I am doing something wrong, but the code implies this should work.

**Comment by jharris4** [comment] 2017-11-10 17:11
Can you provide a bit more detail about what you're trying to do?

Are you trying to include all the `.css` files inside the `src/modules/assets/css/` directory?

If so, are you also using the [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin) to copy the files to your webpack output as well?

I can try and reproduce what you're doing if you can give me a more complete example of your webpack config and directory structure.

**Comment by dylanharty** [comment] 2017-11-10 17:15
@jharris4 Yes, include all the files from a directory into the HTML document after they have been copied by [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin).

I could not figure out the problem with the native library code. So I used glob.sync within the plugin to achieve close to the same result.

```
new HtmlWebpackIncludeAssetsPlugin({
          publicPath: './assets/css/',
          assets: glob.sync("modules/*/assets/css/*.css", { cwd: path.resolve("./src/") }),
          append: false
}),
```

Do you have some code that could achieve the same within your plugin? or do you think my solution is adequate? Thank you.

**Comment by jharris4** [comment] 2017-11-14 10:42
Sorry for the delay, I've been traveling the last few days. There is a unit test for the glob feature, which you can see here:

https://github.com/jharris4/html-webpack-include-assets-plugin/blob/master/spec/index.spec.js#L840

The gist of it is this:

```
new CopyWebpackPlugin([{ from: 'spec/fixtures/g*', to: 'assets/', flatten: true }]),
new HtmlWebpackPlugin(),
new HtmlWebpackIncludeAssetsPlugin({ assets: [{ path: 'assets/', globPath: 'spec/fixtures/', glob: 'g*.js' }, { path: 'assets/', globPath: 'spec/fixtures/', glob: 'g*.css' }], append: true })
```

Have you tried changing your code to look something like this?

```
new CopyWebpackPlugin([{ from: 'modules/*/assets/css/*.css', to: 'assets/', flatten: true }]),
new HtmlWebpackPlugin(),
new HtmlWebpackIncludeAssetsPlugin({ assets: [{ path: 'assets/', globPath: 'modules/', glob: '**/assets/css/*.css' }, append: true })
```

Let me know if something similar to that works, or else please provide a sample modules directory with assets and associated webpack config and I can try to help you further.

**Comment by jharris4** [comment] 2018-01-05 16:05
Closing this issue since there hasn't been any activity for a while.

**Closed by jharris4** 2018-01-05 16:05 UTC
